// Autogenerated file; see corresponding .js

char* repr_b(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xb0()",0));
	if(!SIMPLE(x)) APF(sz,"`b(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%d,",AS_b(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%db",AS_b(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_b(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

char* repr_i(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xi0()",0));
	if(!SIMPLE(x)) APF(sz,"`i(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%d,",AS_i(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%di",AS_i(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_i(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

char* repr_j(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xj0()",0));
	if(!SIMPLE(x)) APF(sz,"`j(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%ld,",AS_j(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%ldj",AS_j(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_j(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

char* repr_o(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xo0()",0));
	if(!SIMPLE(x)) APF(sz,"`o(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%llld,",AS_o(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%llldo",AS_o(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_o(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

char* repr_1(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"x10()",0));
	if(!SIMPLE(x)) APF(sz,"`1(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%p,",AS_1(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%p1",AS_1(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_1(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

char* repr_2(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"x20()",0));
	if(!SIMPLE(x)) APF(sz,"`2(",0);
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) snprintf(s+strlen(s),sz-strlen(s)-1,"%p,",AS_2(x,i)); 
	if(SIMPLE(x)) snprintf(s+strlen(s),sz-strlen(s)-1,"%p2",AS_2(x,i)); 
		else snprintf(s+strlen(s),sz-strlen(s)-1,"...",AS_2(x,i)); 
if(!SIMPLE(x) || x->n>1) APF(sz,")",0);
return s; }

