// Autogenerated file; see corresponding .js

char* repr_b(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xb0()",0));
	if(!SIMPLE(x)) { APF(sz,"'b(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%d,",AS_b(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%db",AS_b(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

char* repr_i(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xi0()",0));
	if(!SIMPLE(x)) { APF(sz,"'i(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%d,",AS_i(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%di",AS_i(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

char* repr_j(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xj0()",0));
	if(!SIMPLE(x)) { APF(sz,"'j(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%ld,",AS_j(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%ldj",AS_j(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

char* repr_f(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"xf0()",0));
	if(!SIMPLE(x)) { APF(sz,"'f(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%0.5f,",AS_f(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%0.5ff",AS_f(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

char* repr_1(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"x10()",0));
	if(!SIMPLE(x)) { APF(sz,"'1(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%p,",AS_1(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%p1",AS_1(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

char* repr_2(VP x,char* s,size_t sz) { int i; 
	IF_RET(x->n==0,APF(sz,"x20()",0));
	if(!SIMPLE(x)) { APF(sz,"'2(...)",0); return s; }
	else if(x->n>1) APF(sz,"(",0);
	for(i=0;i<x->n-1;i++) {
		if(REPR_MAX_ITEMS && i==(REPR_MAX_ITEMS/2)) {
			APF(sz,".. (%d omitted) ..", (x->n)-REPR_MAX_ITEMS);
			i+=REPR_MAX_ITEMS;
			continue;}
		APF(sz,"%p,",AS_2(x,i)); 
	}
	if(SIMPLE(x)) APF(sz,"%p2",AS_2(x,i)); 
if(x->n>1) APF(sz,")",0);
return s; }

