// Autogenerated file; see corresponding .js

static type_info_t TYPES[] = { 
{ 0, 'l', sizeof(VP), "list", &repr_l },
{ 1, 't', sizeof(int), "tag", &repr_t },
{ 2, 'c', sizeof(char), "char", &repr_c },
{ 3, 'b', sizeof(int8_t), "byte", &repr_b },
{ 4, 'i', sizeof(int), "int", &repr_i },
{ 5, 'j', sizeof(__int64_t), "long", &repr_j },
{ 6, 'o', sizeof(__int128_t), "octo", &repr_o },
{ 7, 'f', sizeof(double), "float", &repr_f },
{ 8, 'd', sizeof(VP), "dict", &repr_d },
{ 9, '1', sizeof(unaryFunc*), "f1", &repr_1 },
{ 10, '2', sizeof(binaryFunc*), "f2", &repr_2 },
{ 11, 'p', sizeof(Proj), "proj", &repr_p },
{ 12, 'x', sizeof(VP), "ctx", &repr_x },
};
